# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: rleskine <rleskine@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/03/15 16:29:22 by rleskine          #+#    #+#              #
#    Updated: 2023/08/05 17:46:48 by rleskine         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME		=	philo_bonus
#BONUS		=	checker
SRC			=	philo_utils1.c philo_utils2.c log_utils1.c log_utils2.c
OBJ			=	$(SRC:.c=.o)
CFLAGS		=	-Wall -Wextra -Werror -pthread 
# -fsanitize=address
# remove fsanitize to make leaks work
NPROCS 		=	$(shell sysctl hw.ncpu | grep -o '[0-9]\+')

CC =	cc

all: $(NAME)

$(NAME): %: %.c $(OBJ)
	@$(CC) $(CFLAGS) -o $@ $< $(OBJ)
	@echo "\033[32m[$(NAME)]: Compiled\033[0m"

$(OBJ): %.o: %.c
	@echo "\033[2K[$(NAME)]: Compilation of $< \033[A"
	@$(CC) $(CFLAGS) -c -o $@ $<

#bonus: $(BONUS)

#$(BONUS): %: %.c $(OBJ)
#	$(CC) $(CFLAGS) $(GFX) $(INCLUDE) $(LIBFLAGS) -o $@ $< $(OBJ)

clean:
	@rm -rf $(OBJ)
	@echo "\033[31mObjects files \033[1;31m$(OBJ)\033[1;0m\033[31m removed.\033[0m"

fclean: clean
	@/bin/rm -f $(NAME) $(BONUS)
	@echo "\033[31mBin \033[1;31m$(NAME)\033[1;0m\033[31m removed.\033[0m"

re: fclean all

#.SILENT:
